package gg.essential.loader.stage2.util;

import cpw.mods.jarhandling.JarMetadata;
import cpw.mods.jarhandling.SecureJar;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

public class JarMetadataAccessor {
    private static final Logger LOGGER = LogManager.getLogger();

    private static final Map<Class<?>, Function<SecureJar, JarMetadata>> metadataGetters = new HashMap<>();

    public static JarMetadata getMetadata(SecureJar jar) {
        Class<? extends SecureJar> implClass = jar.getClass();
        Function<SecureJar, JarMetadata> metadataGetter = metadataGetters.get(implClass);
        if (metadataGetter == null) {
            try {
                String implName = implClass.getName();
                switch (implName) {
                    case "org.sinytra.connector.service.DummyVirtualJar":
                        // Used for the dummy fabric-loader mod as well as for code generated by ManninghamMills
                        metadataGetter = __ -> null;
                        break;
                    default: // probably the main ModLauncher-internal impl
                        metadataGetter = UnsafeHacks.makeGetter(implClass.getDeclaredField("metadata"));
                }
            } catch (Throwable t) {
                LOGGER.error("Failed to get metadata from " + implClass + ":", t);
                metadataGetter = __ -> null;
            }
            metadataGetters.put(implClass, metadataGetter);
        }
        return metadataGetter.apply(jar);
    }
}
